import type { WorkerConfig } from "./types";

export const WORKERS: WorkerConfig[] = [
	{
		id: "spoolprices-worker",
		name: "SpoolPrices Worker",
		character: "The Clerk",
		project: "spoolprices.com",
		cron: "0 */2 * * *",
		cronLabel: "Every 2h (price check) + Every 4h (discovery)",
		position: { x: 160, y: 280 },
		personality: "Cheerful shop clerk with a barcode scanner. Always busy checking prices.",
		activities: [
			"Price check (every 2h): fetches stale listings, enqueues to check-queue",
			"Product discovery (every 4h): crawls 13 Shopify stores for new products",
			"Exchange rate update: USD to GBP/EUR/CAD",
			"DLQ consumer: logs failed scrapes to scrape_errors",
		],
		connectedInfra: [
			"d1-spoolprices",
			"kv-spoolprices",
			"r2-images",
			"queue-check",
			"queue-dlq",
		],
		externalApis: [
			"Shopify (13 stores)",
			"Exchange Rate CDN",
			"Resend (email alerts)",
		],
		statusKey: "sprite:status:spoolprices-worker",
		analyticsScriptName: "spoolprices-worker",
		color: "#ef7d57",
	},
	{
		id: "oncstrata-worker",
		name: "OncStrata Worker",
		character: "The Scientist",
		project: "oncstrata",
		cron: "0 */1 * * *",
		cronLabel: "Every hour (2 of 18 indications per run)",
		position: { x: 590, y: 270 },
		personality:
			"Methodical scientist in a lab coat. Walks between stations for different sync tasks.",
		activities: [
			"Trial sync: ClinicalTrials.gov v2 API incremental fetch",
			"Publication sync: PubMed E-utilities esearch+esummary",
			"Congress abstract sync: PubMed search against congress journals",
			"Preprint sync: bioRxiv/medRxiv API",
			"AI brief generation: Llama 3.3 70B (10K neurons/day)",
			"NCCN monitor: guideline scraping",
			"Sponsor financials: SEC EDGAR (weekly)",
			"Patents: openFDA Orange+Purple Book (weekly)",
			"Epidemiology: CDC WONDER/SEER (monthly)",
			"Part D prescribers: CMS Socrata API (monthly)",
		],
		connectedInfra: ["d1-oncstrata", "kv-oncstrata", "ai-terminal"],
		externalApis: [
			"ClinicalTrials.gov",
			"PubMed",
			"bioRxiv/medRxiv",
			"SEC EDGAR",
			"openFDA",
			"CDC WONDER",
			"CMS data.cms.gov",
			"NCCN.org",
		],
		statusKey: "sprite:status:oncstrata-worker",
		analyticsScriptName: "oncstrata-worker",
		color: "#0d9488",
	},
	{
		id: "kol-sync-worker",
		name: "KOL Sync Worker",
		character: "The Librarian",
		project: "nieltran.com",
		cron: "0 3 * * *",
		cronLabel: "Daily at 03:00 UTC",
		position: { x: 920, y: 220 },
		personality:
			"Quiet librarian with a magnifying glass. Activates once daily at 3am to sync provider data.",
		activities: [
			"NPPES provider sync: queries NPI_DB (9.35M rows) for oncology providers",
			"CMS Open Payments sync: fetches payment data for top 200 KOL providers (2021-2023)",
			"KV cache invalidation: clears kol:data:v2",
		],
		connectedInfra: ["d1-nieltran", "d1-npi", "kv-session"],
		externalApis: ["CMS Open Payments"],
		statusKey: "sprite:status:kol-sync-worker",
		analyticsScriptName: "kol-sync-worker",
		color: "#3f8efc",
	},
	{
		id: "oncology-sync-worker",
		name: "Oncology Sync Worker",
		character: "The Courier",
		project: "nieltran.com",
		cron: "0 */2 * * *",
		cronLabel: "Every 2h (8 of 49 categories per batch)",
		position: { x: 1080, y: 350 },
		personality:
			"Energetic courier carrying data packages between services. Batches 49 oncology categories.",
		activities: [
			"Selects batch of 8 categories based on UTC hour",
			"Calls nieltran.com/api/ci/sync for each category",
			"49 categories: 22 solid tumors, 10 heme, 8 molecular targets, 4 modalities",
			"Full rotation every ~14 hours",
		],
		connectedInfra: ["d1-nieltran"],
		externalApis: ["ClinicalTrials.gov (via nieltran API)", "PubMed (via nieltran API)"],
		statusKey: "sprite:status:oncology-sync-worker",
		analyticsScriptName: "oncology-sync-worker",
		color: "#a78bfa",
	},
	{
		id: "nccn-monitor-worker",
		name: "NCCN Monitor Worker",
		character: "The Detective",
		project: "nieltran.com",
		cron: "0 */6 * * *",
		cronLabel: "4x per day",
		position: { x: 1100, y: 200 },
		personality:
			"Watchful detective with a notepad. Regularly checks for NCCN guideline updates.",
		activities: [
			"Scrapes NCCN recently-published-guidelines page",
			"Scrapes category PDF links",
			"Writes version history to D1 nccn_guidelines table",
		],
		connectedInfra: ["d1-nieltran"],
		externalApis: ["NCCN.org"],
		statusKey: "sprite:status:nccn-monitor-worker",
		analyticsScriptName: "nccn-monitor-worker",
		color: "#f59e0b",
	},
];

export function getWorker(id: string): WorkerConfig | undefined {
	return WORKERS.find((w) => w.id === id);
}
